#!/usr/bin/env bash
# Fetch Blockscout and build the explorer fork this project needs.
#
#   ./stack/setup.sh            host processes: also clones and builds the frontend
#   ./stack/setup.sh --docker   containers only: just Blockscout's compose files
#
# Blockscout's code is NOT vendored here — its licence is non-transferable, so you
# fetch it from Blockscout yourself and this script layers our DevNet pages on top:
#
#   1. sparse-clone blockscout/blockscout for its docker-compose files
#   2. clone blockscout/frontend
#   3. copy stack/explorer-overlay/src over the clone (our own code)
#   4. apply stack/explorer-overlay/upstream.patch (nav, metadata, tx page tabs)
#   5. install dependencies and write .env.local
#
# Re-running is safe: existing clones are left alone, the overlay is re-copied and
# the patch is skipped when it is already applied.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE="${DEVNET_WORKSPACE:-$(dirname "$REPO")}"
BLOCKSCOUT_DIR="$WORKSPACE/blockscout"
FRONTEND_DIR="$WORKSPACE/blockscout-frontend"

export DEVNET_RPC_PORT="${DEVNET_RPC_PORT:-8546}"
export DEVNET_CHAIN_ID="${DEVNET_CHAIN_ID:-31337}"
export DEVNET_API_PORT="${DEVNET_API_PORT:-3010}"

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "🚨 $1 is required but not installed." >&2; exit 1; }
}
DOCKER_MODE=0
[ "${1:-}" = "--docker" ] && DOCKER_MODE=1

need git
need docker
# The Docker path builds the explorer in a container and runs Anvil inside the
# control API image, so neither toolchain has to exist on this machine.
if [ "$DOCKER_MODE" = "0" ]; then
  need pnpm
  need anvil
fi

echo "→ Blockscout compose files ($BLOCKSCOUT_DIR)"
if [ ! -d "$BLOCKSCOUT_DIR/.git" ]; then
  git clone --depth 1 --filter=blob:none --sparse https://github.com/blockscout/blockscout.git "$BLOCKSCOUT_DIR"
  git -C "$BLOCKSCOUT_DIR" sparse-checkout set docker-compose
else
  echo "  ✓ already cloned"
fi
cp "$REPO/stack/docker-compose/devnet.override.yml" "$BLOCKSCOUT_DIR/docker-compose/devnet.override.yml"
echo "  ✓ devnet.override.yml in place"

echo "→ Blockscout frontend ($FRONTEND_DIR)"
if [ ! -d "$FRONTEND_DIR/.git" ]; then
  git clone --depth 1 https://github.com/blockscout/frontend.git "$FRONTEND_DIR"
  # `pnpm dev:local` runs `git describe --tags`, which fails on a tagless shallow clone.
  git -C "$FRONTEND_DIR" tag -f devnet-fork-base >/dev/null
else
  echo "  ✓ already cloned"
fi

if [ "$DOCKER_MODE" = "1" ]; then
  cp "$REPO/stack/docker-compose/devnet-stack.yml" "$BLOCKSCOUT_DIR/docker-compose/devnet-stack.yml"
  echo "  ✓ devnet-stack.yml in place"
  echo
  echo "Ready. Start everything with:"
  echo "  ./devnet.sh up --docker"
  exit 0
fi

echo "→ DevNet overlay"
cp -R "$REPO/stack/explorer-overlay/src/." "$FRONTEND_DIR/src/"
echo "  ✓ pages and components copied"

if git -C "$FRONTEND_DIR" apply --check --reverse "$REPO/stack/explorer-overlay/upstream.patch" 2>/dev/null; then
  echo "  ✓ upstream patch already applied"
else
  git -C "$FRONTEND_DIR" apply "$REPO/stack/explorer-overlay/upstream.patch"
  echo "  ✓ upstream patch applied (nav, metadata, transaction tabs, search input)"
fi

echo "→ Frontend dependencies"
# --ignore-scripts: a transitive WebRTC dependency builds native code and fails
# without Xcode CLT / build tools. Nothing here needs it at runtime.
( cd "$FRONTEND_DIR" && pnpm install --ignore-scripts --prefer-offline )
( cd "$FRONTEND_DIR" && pnpm routes:generate >/dev/null )
echo "  ✓ installed"

if [ ! -f "$FRONTEND_DIR/.env.local" ]; then
  cat > "$FRONTEND_DIR/.env.local" <<ENV
# Generated by anvil-devnet-ui/stack/setup.sh
NEXT_PUBLIC_APP_PROTOCOL=http
NEXT_PUBLIC_APP_HOST=localhost
NEXT_PUBLIC_APP_PORT=3000
NEXT_PUBLIC_APP_ENV=development

NEXT_PUBLIC_API_HOST=localhost
NEXT_PUBLIC_API_PROTOCOL=http
NEXT_PUBLIC_API_PORT=80
NEXT_PUBLIC_API_BASE_PATH=/
NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL=ws

NEXT_PUBLIC_STATS_API_HOST=http://localhost:8080
NEXT_PUBLIC_VISUALIZE_API_HOST=http://localhost:8081

NEXT_PUBLIC_NETWORK_NAME=Anvil DevNet
NEXT_PUBLIC_NETWORK_SHORT_NAME=DevNet
NEXT_PUBLIC_NETWORK_ID=${DEVNET_CHAIN_ID}
NEXT_PUBLIC_NETWORK_RPC_URL=http://localhost:${DEVNET_RPC_PORT}
NEXT_PUBLIC_NETWORK_CURRENCY_NAME=Ether
NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL=ETH
NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS=18
NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE=mining
NEXT_PUBLIC_IS_TESTNET=true

NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED=false
NEXT_PUBLIC_AD_BANNER_PROVIDER=none
NEXT_PUBLIC_AD_TEXT_PROVIDER=none
NEXT_PUBLIC_HOMEPAGE_CHARTS=[]
NEXT_PUBLIC_FEATURED_NETWORKS=
NEXT_PUBLIC_NETWORK_EXPLORERS=[]

# server-side only — the browser never talks to the control API directly
DEVNET_API_URL=http://localhost:${DEVNET_API_PORT}
ENV
  echo "  ✓ .env.local written"
else
  echo "  ✓ .env.local kept (delete it to regenerate)"
fi

echo
echo "Done. Start everything with:  ./devnet.sh up"
