/**
 * Compiles contracts/MockERC20.sol and regenerates lib/mockErc20.ts.
 *
 * Needs solc 0.8.28 on PATH; the generated file is committed, so nobody else has
 * to install it. Run with `bun run build:mock-erc20`.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const ROOT = path.join(import.meta.dirname, "..");
const SOURCE = path.join(ROOT, "contracts", "MockERC20.sol");
const OUTPUT = path.join(ROOT, "lib", "mockErc20.ts");

const raw = execFileSync("solc", ["--optimize", "--combined-json", "bin,bin-runtime", SOURCE], {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
});

const contracts = (JSON.parse(raw) as { contracts: Record<string, { bin: string }> }).contracts;
const entry = Object.entries(contracts).find(([name]) => name.endsWith(":MockERC20"));
if (!entry) throw new Error("MockERC20 not found in solc output");

const creation = `0x${entry[1].bin}`;
const version = execFileSync("solc", ["--version"], { encoding: "utf8" }).trim().split("\n").pop();

fs.writeFileSync(
    OUTPUT,
    `// Generated by scripts/buildMockErc20.ts from contracts/MockERC20.sol — do not edit.
// ${version}

/**
 * Creation bytecode of the patcher's stand-in ERC-20. It is *creation* bytecode,
 * not runtime: the constructor is what writes name, symbol, decimals and supply,
 * and {@link file://../lib/codePatcher.ts} replays it in a trace to capture the
 * storage those writes produce.
 *
 * Constructor: (string name, string symbol, uint8 decimals, uint256 supply, address holder)
 */
export const MOCK_ERC20_CREATION_BYTECODE =
    "${creation}" as const;

/** Storage slot of the balances mapping — see the layout comment in the source. */
export const MOCK_ERC20_BALANCE_SLOT = 0;
`
);

console.log(`wrote ${path.relative(ROOT, OUTPUT)} (${creation.length / 2 - 1} bytes of creation bytecode)`);
